### ISSUE TITLE
Could I use some of the frontend?

### ISSUE THREAD

**Issue by dr413677671** [blacktunes/novelai-tag#1]
Hey blacktunes, 
I am working on a stable-diffusion-webui extension to populate and manage promptset previews. Open source proj.

My idea is to integrate my code with a beautiful frontend like this repo.  Just realized that there is no license under the repo. Could I used some of the front end code from your repo? Thanks

**Comment by dr413677671** [comment]
Contact me on qq413677671 if you are interested. We could work together.

**Comment by dr413677671** [comment]
Please checkout https://www.youtube.com/watch?v=9U6-moIJUkk for current details

**Comment by blacktunes** [comment]
需要参考的话就用吧，没关系

**Comment by dr413677671** [comment]
谢啦老哥
